---
- hosts: all
  vars:
    ansible_sudo_pass: balajiv
    jenkins_home: "/home/xbalaji/containers/jenkins"
    artifactory_home: "/home/xbalaji/containers/artifactory"
    gitlab_home: "/home/xbalaji/containers/gitlab"
  tasks:
  - name: test connection
    ping:

  - name: install pip command
    become: yes
    become_method: sudo
    apt:
      name: python-pip
      state: present

  - name: upgrade pip
    become: yes
    pip:
      name : pip
      extra_args: --upgrade
      state: present
    
  - name: install docker.py
    become: yes
    pip:
      name : docker.py
      state: present
    
  - name: docker pull hello-world
    docker_container:
      name : myhello
      image: hello-world
      state: started

  - name: create directory for jenkins container
    file:
      path: "{{ jenkins_home }}"
      state: directory

  - name: docker start jenkins
    become: yes
    docker_container:
      name: jenkins_on_docker
      image: jenkins/jenkins:lts
      volumes:
        - "{{ jenkins_home }}:/var/jenkins_home:z"
      ports: 
        - "8080:8080"
        - "50000:50000"
      state: started
      env: 
        JAVA_OPTS: "-Dhudson.Main.development=true -Djenkins.install.runSetupWizard=false" 
    
  - name: create directory for artifactory container
    file:
      path: "{{ artifactory_home }}"
      state: directory

  - name: docker start artifactory
    become: yes
    docker_container:
      name: artifactory_on_docker
      image: docker.bintray.io/jfrog/artifactory-oss:latest
      volumes:
        - "{{ artifactory_home }}:/var/opt/jfrog/artifactory"
      ports: 
        - "8081:8081"
      state: started
      env: 
    
  - name: create directory for gitlab container
    file: 
      path:  "{{gitlab_home}}/{{item}}"
      state: directory
    with_items:
      [ "etc", "opt", "log" ]

  - name: docker start gitlab
    become: yes
    docker_container:
      name: gitlab_on_docker
      image: gitlab/gitlab-ce
      volumes:
        - "{{ gitlab_home }}/etc:/etc/gitlab:z"
        - "{{ gitlab_home }}/opt:/var/opt/gitlab:z"
        - "{{ gitlab_home }}/log:/var/log/gitlab:z"
      ports: 
        - "10022:22"
        - "10080:80"
        - "10433:443"
      state: started
      env: 
    


