---

#
# This playbook will login using ssh, no authorized keys, interactive login
# to the remote server. 
# The root password is stored in encrypted vault file root_passwd.yml 
#
# may need to install "sshpass" for this to work
#
# execute: ansible-playbook -i hosts raw_df.yml  --ask-vault-pass
#


- hosts: rhel
  gather_facts: False
  tasks:
    - include_vars:
        file: root_passwd.yml

    # use set_fact to assign variables in the task context
    - set_fact:
        ansible_user: root
        ansible_ssh_pass: "{{root_passwd}}"

    - raw: df -h
      register: df
    - debug:
        var: df.stdout_lines

    - raw: uname -a
      register: uname
    - debug:
        var: uname.stdout_lines

