---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  # gathers facts and registers the output as `ec2_facts`
  - name: Gather EC2 facts.
    ec2_remote_facts:
      region: "{{ region | default(us-east-1) }}"
    register: ec2_facts

  # debug that output
  - name: Debug
    debug: 
      msg: "{{ aws_ec2_facts }}"

  # print out all running instance IDs and their IP addresses.
  - name: Get only running instance IP addresses.
    debug:
      msg: "Instance: {{ item.0 }} has IP address: {{ item.1 }}"
    with_together:
      - "{{ aws_ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='tags.Name')|list }}"
      - "{{ aws_ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='private_ip_address')|list }}"
