---
- hosts: all
  name: ansible-vault-demo
  - tasks:
    include ec2.yml
    - debug:
      msg: "ec2_access_key is {{ec2_access_key}}, ec2_secret_key is {{ec2_secret_key}}" 


#  aws_access_key: "{{ec2_access_key}}"
#  aws_secret_key: "{{ec2_secret_key}}"
