---
- hosts: all
  gather_facts: False
  remote_user: root

  tasks:
    - name: create /root/.ssh
      file:
        path: /root/.ssh
        state: directory
        mode: 0700

    # upload ssh key
    - name: update authorized_key
      authorized_key:
        user: root
        exclusive: no
        state: present
        key: "{{ lookup('file', '/home/xbalaji/.ssh/id_rsa.pub') }}"
        manage_dir: yes


# now run this playbook 
# ansible-playbook -i <inventory> <this_playbook>
